from io import BytesIO
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from app.utils.clean_ai_plot_code import clean_ai_plot_code


def execute_plot_code(plot_code, results):
    """
    Execute the Python plot code generated by the AI.
    """
    buf = BytesIO()
    try:
        df = pd.DataFrame(results)  # Convert results to dataframe

        # Define the global variables that the AI-generated code might use
        exec_globals = {
            'plt': plt,
            'sns': sns,
            'pd': pd,
            'data': df  # Pass the dataframe to be used in the generated code
        }

        print(f"Executing plot_code: {plot_code}")\

        # Execute the AI-generated Python code
        exec(plot_code, exec_globals)

        # Save the plot to a buffer
        if plt.get_fignums():  # Check if any figure was generated
            plt.savefig(buf, format='png')
            plt.close('all')
            buf.seek(0)
            return buf
        else:
            raise ValueError("The generated Python code did not create a plot.")

    except Exception as e:
        print(f"Error executing plot code: {str(e)}")
        return None
