from io import BytesIO
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import logging

logger = logging.getLogger(__name__)


def execute_plot_code(plot_code, results):
    """
    Execute the Python plot code generated by the AI.
    """
    buf = BytesIO()
    try:
        # Convert the SQL query results to a Pandas DataFrame
        df = pd.DataFrame(results)

        # Log the DataFrame to ensure it is correctly formatted
        logger.info(f"DataFrame for plot: {df.head()}")

        # Define the global variables that the AI-generated code might use
        exec_globals = {
            'plt': plt,
            'sns': sns,
            'pd': pd,
            'data': df  # Pass the dataframe to be used in the generated code
        }

        # Log the generated plot code for debugging
        logger.info(f"Executing plot code: {plot_code}")

        # Execute the AI-generated Python code
        exec(plot_code, exec_globals)

        # Save the plot to a buffer if a figure is generated
        if plt.get_fignums():  # Check if any figure was generated
            plt.savefig(buf, format='png')
            plt.close('all')
            buf.seek(0)
            return buf
        else:
            raise ValueError("The generated Python code did not create a plot.")

    except Exception as e:
        logger.error(f"Error executing plot code: {str(e)}")
        return None
